# Generated by Django 4.0.3 on 2022-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_start_tech',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
