# Generated by Django 4.0.3 on 2022-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trich',
            field=models.CharField(default='', max_length=100),
        ),
    ]
