# Generated by Django 4.0.3 on 2022-03-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_trich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='trich',
        ),
    ]
