# Generated by Django 4.0.3 on 2022-04-13 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_post_likes_delete_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtalk',
            name='likes',
            field=models.ManyToManyField(related_name='techtalk_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techtalk',
            name='subcribes',
            field=models.ManyToManyField(related_name='techtalk_subcribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TechtalkLike',
        ),
    ]
