# Generated by Django 4.0.3 on 2022-04-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_techtalk_likes_techtalk_subcribes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TechtalkSubcribe',
        ),
    ]
