# Generated by Django 4.0.3 on 2022-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='diff',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Discussion'), (1, 'Learning')], default=0),
        ),
    ]
