# Generated by Django 4.0.3 on 2022-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('discussion', 'Discussion'), ('learning', 'Learning')], default='discussion'),
        ),
    ]
